const Lang = {
  en: {
    placeholder: {
      firstName: 'First name',
      secondName: 'Second name',
      address: 'Address',
      phone: 'Phone number',
      email: 'Email',
      photo: 'Photo',
      description: 'Description',
      university: 'University',
      city: 'City',
      degree: 'Degree',
      subject: 'Subject',
      dateFrom: 'from',
      dateTo: 'to',
      company: 'Company',
      position: 'Position',
      duties: 'Duties',
      achievements: 'Achievements',
      language: 'Language',
      level: 'Level',
      sertificates: 'Sertificates',
      skills: 'Skills',
    },
    header: {
      personalInfo: 'Personal information',
      education: 'Education',
      experience: 'Experience',
      languages: 'Languages',
      skills: 'Skills',
      certifications: 'Certifications',
    },
    button: {
      add: 'Add',
      delete: 'Delete',
      load: 'Load',
      save: 'Save',
      input: 'Input',
      preview: 'Preview',
    },
    title: {
      contact: 'Contact',
      address: 'Address:',
      phone: 'Phone:',
      email: 'Email:',
      description: 'Summary',
      languages: 'Languages',
      education: 'Education',
      experience: 'Experience',
      skills: 'Skill hilights',
      certifications: 'Certificates',
    },
    separator: {
      to: 'to',
    },
  },
  ru: {
    placeholder: {
      firstName: 'Имя',
      secondName: 'Фамилия',
      address: 'Адрес',
      phone: 'Номер телефона',
      email: 'Эл. почта',
      photo: 'Фотография',
      description: 'Описание',
      university: 'Учебное заведение',
      city: 'Город',
      degree: 'Ученая степень',
      subject: 'Специальность',
      dateFrom: 'с',
      dateTo: 'до',
      company: 'Компания',
      position: 'Должность',
      duties: 'Должностные обязанности',
      achievements: 'Достижения',
      language: 'Язык',
      level: 'Уровень владения',
      sertificates: 'Сертификаты и награды',
      skills: 'Навыки и умения',
    },
    header: {
      personalInfo: 'Личная информация',
      education: 'Образование',
      experience: 'Опыт',
      languages: 'Языки',
      skills: 'Навыки и умения',
      certifications: 'Сертификаты и награды',
    },
    button: {
      add: 'Добавить',
      delete: 'Удалить',
      load: 'Загрузить',
      save: 'Сохранить',
      input: 'Ввод',
      preview: 'Просмотр',
    },
    title: {
      contact: 'Контакты',
      address: 'Адрес:',
      phone: 'Тел.:',
      email: 'Эл. почта:',
      description: 'Ключевая информация',
      languages: 'Языки',
      education: 'Образование',
      experience: 'Опыт',
      skills: 'Навыки и умения',
      certifications: 'Сертификаты и награды',
    },
    separator: {
      to: 'до',
    },
  },
  ua: {
    placeholder: {
      firstName: "Ім'я",
      secondName: 'Призвище',
      address: 'Адреса',
      phone: 'Номер телефону',
      email: 'Ел. пошта',
      photo: 'Світлина',
      description: 'Опис',
      university: 'Учбовий заклад',
      city: 'Місто',
      degree: 'Наукова ступень',
      subject: 'Фах',
      dateFrom: 'з',
      dateTo: 'до',
      company: 'Компанія',
      position: 'Посада',
      duties: "Посадові обов'язки",
      achievements: 'Досягнення',
      language: 'Мова',
      level: 'Рівень володіння',
      sertificates: 'Сертіфікаты і винагороди',
      skills: 'Навички та вміння',
    },
    header: {
      personalInfo: 'Особиста інформація',
      education: 'Освіта',
      experience: 'Досвід',
      languages: 'Мови',
      skills: 'Навички та вміння',
      certifications: 'Сертіфікати і нагороди',
    },
    button: {
      add: 'Додати',
      delete: 'Видалити',
      load: 'Завантажити',
      save: 'Зберегти',
      input: 'Введення',
      preview: 'Перегляд',
    },
    title: {
      contact: 'Контакти',
      address: 'Адреса:',
      phone: 'Тел.:',
      email: 'Ел. пошта:',
      description: 'Ключова інформація',
      languages: 'Мови',
      education: 'Освіта',
      experience: 'Досвід роботи',
      skills: 'Навички та вміння',
      certifications: 'Сертіфікати і нагороди',
    },
    separator: {
      to: 'до',
    },
  },
};
export default Lang;
